### ISSUE TITLE
Errors in Knowledge items

### ISSUE THREAD

**Issue by laring141** [N6REJ/BetterBags_Bears_Ultimate#13]
TWW_Knowledge.lua does not contain some weekly items

#Blacksmithing
225232, -- Coreway Billet

 -- #Engineering

225228, -- Rust-Locked Mechanism
225229, -- Earthen Induction Coil

-- #Inscription

225226, -- Striated Inkstone

-- #Jewelcrafting

225224, -- Diaphanous Gem Shards

Also, 225234, -- Alchemical Sediment is Alchemy item, not Herbalism

**Comment by laring141** [comment]
Also, -- #Engineering
222621, -- Algari Treatise on Engineering

**Comment by N6REJ** [comment]
fixed in 2024.11.4
