### ISSUE TITLE
Duskweave 2 and 3 have the wrong ID

### ISSUE THREAD

**Issue by sean-kang** [N6REJ/BetterBags_Bears_Ultimate#5]
I saw the Duskweave 2 was not in Cloth category and found out the following items had the wrong ID.

https://github.com/N6REJ/BetterBags_Bears_Ultimate/blob/54f4b2efe3753c880996ca746b61d10833343b3b/Databases/TWW/TWW_Tailoring.lua#L61

Should be changed to -> Duskweave 2: 228233

https://github.com/N6REJ/BetterBags_Bears_Ultimate/blob/54f4b2efe3753c880996ca746b61d10833343b3b/Databases/TWW/TWW_Tailoring.lua#L62

Should be changed to -> Duskweave 3: 228234

**Comment by jwaisner** [comment]
https://github.com/N6REJ/BetterBags_Bears_Ultimate/pull/7 fixed this.
